[package]
name = "keev"
version = "0.1.0"
authors = ["Usairim Isani <usairim.isani@outlook.com>"]
edition = "2018"
build = "build.rs"


[dependencies]
anyhow = "1.0.34"
async-raft = "0.5.5"
capnp-futures = "0.13.1"
capnp = "0.13.6"
capnp-rpc = "0.13.1"


[build-dependencies]
capnpc = "0.13"